-- Q1. What is the total revenue generated by male vs. female customers?

SELECT
	gender,
    sum(purchase_amt)
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT 
	customer_id,
    purchase_amt
FROM customer
where purchase_amt > (
	SELECT 
		avg(purchase_amt)
	FROM customer 
    ) AND discount_applied='YES';

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, avg(review_rating)
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT 
	shipping_type, 
    avg(purchase_amt)
FROM customer
GROUP BY shipping_type
HAVING shipping_type IN ('Standard', 'Express');

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT
	subscription_status,
    count(customer_id),
    avg(purchase_amt),
    sum(purchase_amt)
FROM customer
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
100*sum(case when discount_applied = 'YES' then 1 else 0 end) / count(*) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with 
customer_type as (
	select customer_id, previous_purchases,
    case 
		when previous_purchases = 1 then 'new'
        when previous_purchases between 2 and 10 then 'returning'
        else 'loyal'
	end as customer_segment
    from customer
)
select 
	customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;   

-- Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?

SELECT 
    age_group,
    SUM(purchase_amt) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
